#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_ApplicationCcFri_CcOf_AFs_Status_MTfI
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("I accept", 0)]
		IAccept = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("I need to upload supporting documents", 1)]
		INeedToUploadSupportingDocuments = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_ApplicationCcFri_CcOf_ChargeFeeCcFri
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No", 1, "#0000ff")]
		No = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yes", 0, "#0000ff")]
		Yes = 100000000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_ApplicationCcFri_CcOf_FeeCorrectCcFri
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No", 1, "#0000ff")]
		No = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yes", 0, "#0000ff")]
		Yes = 100000000,
	}
	
	/// <summary>
	/// Status of the Application CCFRI
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_ApplicationCcFri_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Application CCFRI
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_ApplicationCcFri_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Action Required", 5)]
		ActionRequired = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approved", 2)]
		Approved = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ineligible", 4)]
		Ineligible = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MTFI Action Required", 10)]
		MtfiActionRequired = 13,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MTFI Approved", 9)]
		MtfiApproved = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("MTFI Requested", 8)]
		MtfiRequested = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New", 7)]
		New = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Approved", 3)]
		NotApproved = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opt-Out", 6)]
		OptOut = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Submitted", 0)]
		Submitted = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ccof_applicationccfri")]
	public partial class CcOf_ApplicationCcFri : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the ccof_applicationccfri entity
		/// </summary>
		public partial class Fields
		{
			public const string Business_Unit_CcOf_ApplicationCcFri = "business_unit_ccof_applicationccfri";
			public const string CcOf_Adjudication_CcFri_Facility_Application = "CcOf_Adjudication_CcFri_Facility_Application";
			public const string CcOf_Adjudication_CcFri_Facility_PreviousCcFri = "CcOf_Adjudication_CcFri_Facility_PreviousCcFri";
			public const string CcOf_AFs_ApplicationCcFri = "CcOf_AFs_ApplicationCcFri";
			public const string CcOf_AFs_History_CcOf_ApplicationCcFri = "CcOf_AFs_History_CcOf_ApplicationCcFri";
			public const string CcOf_AFs_Status = "ccof_afs_status";
			public const string CcOf_AFs_Status_MTfI = "ccof_afs_status_mtfi";
			public const string CcOf_AFs_Status_MtFinAMe = "ccof_afs_status_mtfiname";
			public const string CcOf_AFs_StatusName = "ccof_afs_statusname";
			public const string CcOf_AFsEmailType = "ccof_afsemailtype";
			public const string CcOf_AFsEmailTypeName = "ccof_afsemailtypename";
			public const string CcOf_Application = "ccof_application";
			public const string CcOf_Application_CcFri_CCc = "CcOf_Application_CcFri_CCc";
			public const string CcOf_ApplicationCcFri_Application_CcOf_Ap = "ccof_applicationccfri_Application_ccof_ap";
			public const string CcOf_ApplicationCcFri_Facility = "ccof_applicationccfri_Facility";
			public const string ReferencingCcOf_ApplicationCcFri_PreviousCcFri = "ccof_applicationccfri_PreviousCCFRI";
			public const string CcOf_ApplicationCcFri_Region = "ccof_applicationccfri_Region";
			public const string CcOf_ApplicationCcFri_Region3PctMedian = "ccof_applicationccfri_Region3PctMedian";
			public const string CcOf_ApplicationCcFri_RegIoNnMfBenchmark = "ccof_applicationccfri_RegionNMFBenchmark";
			public const string CcOf_ApplicationCcFriId = "ccof_applicationccfriid";
			public const string Id = "ccof_applicationccfriid";
			public const string CcOf_ApplicationName = "ccof_applicationname";
			public const string CcOf_CcFri_Closure_Application_CcFri = "CcOf_CcFri_Closure_Application_CcFri";
			public const string CcOf_CcFriOptIn = "ccof_ccfrioptin";
			public const string CcOf_CcFriOpTinName = "ccof_ccfrioptinname";
			public const string CcOf_CcOf_Change_Request_New_Facility_CcFri_Cc = "CcOf_CcOf_Change_Request_New_Facility_CcFri_Cc";
			public const string CcOf_Change_Request_MTfI_Application_CcFri = "CcOf_Change_Request_MTfI_Application_CcFri";
			public const string CcOf_ChargeFeeCcFri = "ccof_chargefeeccfri";
			public const string CcOf_ChargeFeeCcFriName = "ccof_chargefeeccfriname";
			public const string CcOf_ClosureFormComplete = "ccof_closureformcomplete";
			public const string CcOf_ClosureFormCompleteName = "ccof_closureformcompletename";
			public const string CcOf_DM_SourceId = "ccof_dm_sourceid";
			public const string CcOf_Facility = "ccof_facility";
			public const string CcOf_FacilityName = "ccof_facilityname";
			public const string CcOf_FacilityYomiName = "ccof_facilityyominame";
			public const string CcOf_FAcLiLiTyId = "ccof_faclilityid";
			public const string CcOf_FeeCorrectCcFri = "ccof_feecorrectccfri";
			public const string CcOf_FeeCorrectCcFriName = "ccof_feecorrectccfriname";
			public const string CcOf_FormComplete = "ccof_formcomplete";
			public const string CcOf_FormCompleteName = "ccof_formcompletename";
			public const string CcOf_Has_NMf = "ccof_has_nmf";
			public const string CcOf_Has_NMfName = "ccof_has_nmfname";
			public const string CcOf_Has_RfI = "ccof_has_rfi";
			public const string CcOf_Has_RfIName = "ccof_has_rfiname";
			public const string CcOf_InformationCcFri = "ccof_informationccfri";
			public const string CcOf_Name = "ccof_name";
			public const string CcOf_NMf_FormComplete = "ccof_nmf_formcomplete";
			public const string CcOf_NMf_FormCompleteName = "ccof_nmf_formcompletename";
			public const string CcOf_Opt_In_Date = "ccof_opt_in_date";
			public const string CcOf_PreviousCcFri = "ccof_previousccfri";
			public const string CcOf_PreviousCcFriName = "ccof_previousccfriname";
			public const string CcOf_Region = "ccof_region";
			public const string CcOf_Region3PctMedian = "ccof_region3pctmedian";
			public const string CcOf_Region3PctMedianName = "ccof_region3pctmedianname";
			public const string CcOf_RegionName = "ccof_regionname";
			public const string CcOf_RegIoNnMfBenchmark = "ccof_regionnmfbenchmark";
			public const string CcOf_RegIoNnMfBenchmarkName = "ccof_regionnmfbenchmarkname";
			public const string CcOf_RfI_FormComplete = "ccof_rfi_formcomplete";
			public const string CcOf_RfI_FormCompleteName = "ccof_rfi_formcompletename";
			public const string CcOf_RfI_PFI_NMf_ApplicationCcFri = "CcOf_RfI_PFI_NMf_ApplicationCcFri";
			public const string CcOf_RfIpFI_ApplicationCcFri = "CcOf_RfIpFI_ApplicationCcFri";
			public const string CcOf_Unlock_AFs = "ccof_unlock_afs";
			public const string CcOf_Unlock_AFsEnable = "ccof_unlock_afsenable";
			public const string CcOf_Unlock_AFsEnableName = "ccof_unlock_afsenablename";
			public const string CcOf_Unlock_AFsName = "ccof_unlock_afsname";
			public const string CcOf_Unlock_CcFri = "ccof_unlock_ccfri";
			public const string CcOf_Unlock_CcFriName = "ccof_unlock_ccfriname";
			public const string CcOf_Unlock_NMf_RfI = "ccof_unlock_nmf_rfi";
			public const string CcOf_Unlock_NMf_RfIName = "ccof_unlock_nmf_rfiname";
			public const string CcOf_Unlock_RfI = "ccof_unlock_rfi";
			public const string CcOf_Unlock_RfIName = "ccof_unlock_rfiname";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ExchangerAte = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Lk_CcOf_ApplicationCcFri_CreatedBy = "lk_ccof_applicationccfri_createdby";
			public const string Lk_CcOf_ApplicationCcFri_CreatedOnBehalfBy = "lk_ccof_applicationccfri_createdonbehalfby";
			public const string Lk_CcOf_ApplicationCcFri_ModifiedBy = "lk_ccof_applicationccfri_modifiedby";
			public const string Lk_CcOf_ApplicationCcFri_ModifiedOnBehalfBy = "lk_ccof_applicationccfri_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ReferencedCcOf_ApplicationCcFri_PreviousCcFri = "ReferencedCcOf_ApplicationCcFri_PreviousCcFri";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrency_CcOf_ApplicationCcFri = "TransactionCurrency_ccof_applicationccfri";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string User_CcOf_ApplicationCcFri = "user_ccof_applicationccfri";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationCcFri(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationCcFri(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationCcFri(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		public const string AlternateKeys = "ccof_application,ccof_facility|ccof_dm_sourceid";
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationCcFri() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "ccof_applicationccfriid";
		
		public const string PrimaryNameAttribute = "ccof_name";
		
		public const string EntitySchemaName = "ccof_applicationccfri";
		
		public const string EntityLogicalName = "ccof_applicationccfri";
		
		public const string EntityLogicalCollectionName = "ccof_applicationccfris";
		
		public const string EntitySetName = "ccof_applicationccfris";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_afs_status")]
		public virtual CcOf_Agreement_Status? CcOf_AFs_Status
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_Agreement_Status?)(EntityOptionSetEnum.GetEnum(this, "ccof_afs_status")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_afs_status", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_afs_status_mtfi")]
		public virtual CcOf_ApplicationCcFri_CcOf_AFs_Status_MTfI? CcOf_AFs_Status_MTfI
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_ApplicationCcFri_CcOf_AFs_Status_MTfI?)(EntityOptionSetEnum.GetEnum(this, "ccof_afs_status_mtfi")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_afs_status_mtfi", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_afs_status_mtfiname")]
		public string CcOf_AFs_Status_MtFinAMe
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_afs_status_mtfi"))
				{
					return this.FormattedValues["ccof_afs_status_mtfi"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_afs_statusname")]
		public string CcOf_AFs_StatusName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_afs_status"))
				{
					return this.FormattedValues["ccof_afs_status"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_afsemailtype")]
		public virtual CcOf_AFsEmailType? CcOf_AFsEmailType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_AFsEmailType?)(EntityOptionSetEnum.GetEnum(this, "ccof_afsemailtype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_afsemailtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_afsemailtypename")]
		public string CcOf_AFsEmailTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_afsemailtype"))
				{
					return this.FormattedValues["ccof_afsemailtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_application")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_Application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_application");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_application", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_applicationccfriid")]
		public System.Nullable<System.Guid> CcOf_ApplicationCcFriId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ccof_applicationccfriid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_applicationccfriid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_applicationccfriid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.CcOf_ApplicationCcFriId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_applicationname")]
		public string CcOf_ApplicationName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_application"))
				{
					return this.FormattedValues["ccof_application"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_ccfrioptin")]
		public virtual CcOf_YesNo? CcOf_CcFriOptIn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_YesNo?)(EntityOptionSetEnum.GetEnum(this, "ccof_ccfrioptin")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_ccfrioptin", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_ccfrioptinname")]
		public string CcOf_CcFriOpTinName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_ccfrioptin"))
				{
					return this.FormattedValues["ccof_ccfrioptin"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_chargefeeccfri")]
		public virtual CcOf_ApplicationCcFri_CcOf_ChargeFeeCcFri? CcOf_ChargeFeeCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_ApplicationCcFri_CcOf_ChargeFeeCcFri?)(EntityOptionSetEnum.GetEnum(this, "ccof_chargefeeccfri")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_chargefeeccfri", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_chargefeeccfriname")]
		public string CcOf_ChargeFeeCcFriName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_chargefeeccfri"))
				{
					return this.FormattedValues["ccof_chargefeeccfri"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_closureformcomplete")]
		public System.Nullable<bool> CcOf_ClosureFormComplete
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ccof_closureformcomplete");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_closureformcomplete", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_closureformcompletename")]
		public string CcOf_ClosureFormCompleteName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_closureformcomplete"))
				{
					return this.FormattedValues["ccof_closureformcomplete"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_dm_sourceid")]
		public string CcOf_DM_SourceId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ccof_dm_sourceid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_dm_sourceid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_facility")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_Facility
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_facility");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_facility", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_facilityname")]
		public string CcOf_FacilityName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_facility"))
				{
					return this.FormattedValues["ccof_facility"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_facilityyominame")]
		public string CcOf_FacilityYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_facility"))
				{
					return this.FormattedValues["ccof_facility"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_faclilityid")]
		public string CcOf_FAcLiLiTyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ccof_faclilityid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_feecorrectccfri")]
		public virtual CcOf_ApplicationCcFri_CcOf_FeeCorrectCcFri? CcOf_FeeCorrectCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_ApplicationCcFri_CcOf_FeeCorrectCcFri?)(EntityOptionSetEnum.GetEnum(this, "ccof_feecorrectccfri")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_feecorrectccfri", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_feecorrectccfriname")]
		public string CcOf_FeeCorrectCcFriName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_feecorrectccfri"))
				{
					return this.FormattedValues["ccof_feecorrectccfri"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_formcomplete")]
		public System.Nullable<bool> CcOf_FormComplete
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ccof_formcomplete");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_formcomplete", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_formcompletename")]
		public string CcOf_FormCompleteName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_formcomplete"))
				{
					return this.FormattedValues["ccof_formcomplete"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_has_nmf")]
		public System.Nullable<bool> CcOf_Has_NMf
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ccof_has_nmf");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_has_nmf", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_has_nmfname")]
		public string CcOf_Has_NMfName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_has_nmf"))
				{
					return this.FormattedValues["ccof_has_nmf"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_has_rfi")]
		public System.Nullable<bool> CcOf_Has_RfI
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ccof_has_rfi");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_has_rfi", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_has_rfiname")]
		public string CcOf_Has_RfIName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_has_rfi"))
				{
					return this.FormattedValues["ccof_has_rfi"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Is there any other information about this facility you would like us to know?
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_informationccfri")]
		public string CcOf_InformationCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ccof_informationccfri");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_informationccfri", value);
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_name")]
		public string CcOf_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ccof_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_nmf_formcomplete")]
		public System.Nullable<bool> CcOf_NMf_FormComplete
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ccof_nmf_formcomplete");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_nmf_formcomplete", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_nmf_formcompletename")]
		public string CcOf_NMf_FormCompleteName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_nmf_formcomplete"))
				{
					return this.FormattedValues["ccof_nmf_formcomplete"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_opt_in_date")]
		public System.Nullable<System.DateTime> CcOf_Opt_In_Date
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ccof_opt_in_date");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_opt_in_date", value);
			}
		}
		
		/// <summary>
		/// CCFRI submitted last year
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_previousccfri")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_PreviousCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_previousccfri");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_previousccfri", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_previousccfriname")]
		public string CcOf_PreviousCcFriName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_previousccfri"))
				{
					return this.FormattedValues["ccof_previousccfri"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Current Fee Region from associated Facility
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_region")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_Region
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_region");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_region", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_region3pctmedian")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_Region3PctMedian
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_region3pctmedian");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_region3pctmedian", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_region3pctmedianname")]
		public string CcOf_Region3PctMedianName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_region3pctmedian"))
				{
					return this.FormattedValues["ccof_region3pctmedian"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_regionname")]
		public string CcOf_RegionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_region"))
				{
					return this.FormattedValues["ccof_region"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_regionnmfbenchmark")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_RegIoNnMfBenchmark
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_regionnmfbenchmark");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_regionnmfbenchmark", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_regionnmfbenchmarkname")]
		public string CcOf_RegIoNnMfBenchmarkName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_regionnmfbenchmark"))
				{
					return this.FormattedValues["ccof_regionnmfbenchmark"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_rfi_formcomplete")]
		public System.Nullable<bool> CcOf_RfI_FormComplete
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ccof_rfi_formcomplete");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_rfi_formcomplete", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_rfi_formcompletename")]
		public string CcOf_RfI_FormCompleteName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_rfi_formcomplete"))
				{
					return this.FormattedValues["ccof_rfi_formcomplete"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_afs")]
		public virtual CcOf_YesNo? CcOf_Unlock_AFs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_YesNo?)(EntityOptionSetEnum.GetEnum(this, "ccof_unlock_afs")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_unlock_afs", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_afsenable")]
		public virtual CcOf_YesNo? CcOf_Unlock_AFsEnable
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_YesNo?)(EntityOptionSetEnum.GetEnum(this, "ccof_unlock_afsenable")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_unlock_afsenable", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_afsenablename")]
		public string CcOf_Unlock_AFsEnableName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_unlock_afsenable"))
				{
					return this.FormattedValues["ccof_unlock_afsenable"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_afsname")]
		public string CcOf_Unlock_AFsName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_unlock_afs"))
				{
					return this.FormattedValues["ccof_unlock_afs"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_ccfri")]
		public virtual CcOf_YesNo? CcOf_Unlock_CcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_YesNo?)(EntityOptionSetEnum.GetEnum(this, "ccof_unlock_ccfri")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_unlock_ccfri", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_ccfriname")]
		public string CcOf_Unlock_CcFriName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_unlock_ccfri"))
				{
					return this.FormattedValues["ccof_unlock_ccfri"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_nmf_rfi")]
		public virtual CcOf_YesNo? CcOf_Unlock_NMf_RfI
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_YesNo?)(EntityOptionSetEnum.GetEnum(this, "ccof_unlock_nmf_rfi")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_unlock_nmf_rfi", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_nmf_rfiname")]
		public string CcOf_Unlock_NMf_RfIName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_unlock_nmf_rfi"))
				{
					return this.FormattedValues["ccof_unlock_nmf_rfi"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_rfi")]
		public virtual CcOf_YesNo? CcOf_Unlock_RfI
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_YesNo?)(EntityOptionSetEnum.GetEnum(this, "ccof_unlock_rfi")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_unlock_rfi", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_unlock_rfiname")]
		public string CcOf_Unlock_RfIName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_unlock_rfi"))
				{
					return this.FormattedValues["ccof_unlock_rfi"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangerAte
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("owningbusinessunit", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Application CCFRI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual CcOf_ApplicationCcFri_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_ApplicationCcFri_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Application CCFRI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual CcOf_ApplicationCcFri_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_ApplicationCcFri_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N ccof_adjudication_ccfri_facility_Application
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_adjudication_ccfri_facility_Application")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_Adjudication_CcFri_Facility> CcOf_Adjudication_CcFri_Facility_Application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_Adjudication_CcFri_Facility>("ccof_adjudication_ccfri_facility_Application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_Adjudication_CcFri_Facility>("ccof_adjudication_ccfri_facility_Application", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_adjudication_ccfri_facility_PreviousCCFRI
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_adjudication_ccfri_facility_PreviousCCFRI")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_Adjudication_CcFri_Facility> CcOf_Adjudication_CcFri_Facility_PreviousCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_Adjudication_CcFri_Facility>("ccof_adjudication_ccfri_facility_PreviousCCFRI", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_Adjudication_CcFri_Facility>("ccof_adjudication_ccfri_facility_PreviousCCFRI", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_afs_applicationccfri
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_afs_applicationccfri")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_ApProvable_Fee_Schedule> CcOf_AFs_ApplicationCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_ApProvable_Fee_Schedule>("ccof_afs_applicationccfri", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_ApProvable_Fee_Schedule>("ccof_afs_applicationccfri", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_afs_history_ccof_applicationccfri
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_afs_history_ccof_applicationccfri")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_ApProvable_Fee_Schedule_History> CcOf_AFs_History_CcOf_ApplicationCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_ApProvable_Fee_Schedule_History>("ccof_afs_history_ccof_applicationccfri", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_ApProvable_Fee_Schedule_History>("ccof_afs_history_ccof_applicationccfri", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_application_ccfri_ccc
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_application_ccfri_ccc")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_Application_CcFri_ChildCareCategory> CcOf_Application_CcFri_CCc
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_Application_CcFri_ChildCareCategory>("ccof_application_ccfri_ccc", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_Application_CcFri_ChildCareCategory>("ccof_application_ccfri_ccc", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_applicationccfri_PreviousCCFRI
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationccfri_PreviousCCFRI", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_ApplicationCcFri> ReferencedCcOf_ApplicationCcFri_PreviousCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_ApplicationCcFri>("ccof_applicationccfri_PreviousCCFRI", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_ApplicationCcFri>("ccof_applicationccfri_PreviousCCFRI", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_ccfri_closure_application_ccfri
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccfri_closure_application_ccfri")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_Application_CcFri_Closure> CcOf_CcFri_Closure_Application_CcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_Application_CcFri_Closure>("ccof_ccfri_closure_application_ccfri", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_Application_CcFri_Closure>("ccof_ccfri_closure_application_ccfri", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_ccof_change_request_new_facility_ccfri_cc
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_change_request_new_facility_ccfri_cc")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_Change_Request_New_Facility> CcOf_CcOf_Change_Request_New_Facility_CcFri_Cc
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_Change_Request_New_Facility>("ccof_ccof_change_request_new_facility_ccfri_cc", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_Change_Request_New_Facility>("ccof_ccof_change_request_new_facility_ccfri_cc", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_change_request_mtfi_application_ccfri
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_change_request_mtfi_application_ccfri")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_Change_Request_MTfI> CcOf_Change_Request_MTfI_Application_CcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_Change_Request_MTfI>("ccof_change_request_mtfi_application_ccfri", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_Change_Request_MTfI>("ccof_change_request_mtfi_application_ccfri", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_rfi_pfi_nmf_ApplicationCCFRI
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_rfi_pfi_nmf_ApplicationCCFRI")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_RfI_PFI_NMf> CcOf_RfI_PFI_NMf_ApplicationCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_RfI_PFI_NMf>("ccof_rfi_pfi_nmf_ApplicationCCFRI", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_RfI_PFI_NMf>("ccof_rfi_pfi_nmf_ApplicationCCFRI", null, value);
			}
		}
		
		/// <summary>
		/// 1:N ccof_rfipfi_ApplicationCCFRI
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_rfipfi_ApplicationCCFRI")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_RfIpFI> CcOf_RfIpFI_ApplicationCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_RfIpFI>("ccof_rfipfi_ApplicationCCFRI", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_RfIpFI>("ccof_rfipfi_ApplicationCCFRI", null, value);
			}
		}
		
		/// <summary>
		/// N:1 business_unit_ccof_applicationccfri
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_ccof_applicationccfri")]
		public DataverseModel.BusinessUnit Business_Unit_CcOf_ApplicationCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.BusinessUnit>("business_unit_ccof_applicationccfri", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.BusinessUnit>("business_unit_ccof_applicationccfri", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationccfri_Application_ccof_ap
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_application")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationccfri_Application_ccof_ap")]
		public DataverseModel.CcOf_Application CcOf_ApplicationCcFri_Application_CcOf_Ap
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Application>("ccof_applicationccfri_Application_ccof_ap", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Application>("ccof_applicationccfri_Application_ccof_ap", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationccfri_Facility
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_facility")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationccfri_Facility")]
		public DataverseModel.Account CcOf_ApplicationCcFri_Facility
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.Account>("ccof_applicationccfri_Facility", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.Account>("ccof_applicationccfri_Facility", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationccfri_PreviousCCFRI
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_previousccfri")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationccfri_PreviousCCFRI", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DataverseModel.CcOf_ApplicationCcFri ReferencingCcOf_ApplicationCcFri_PreviousCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_ApplicationCcFri>("ccof_applicationccfri_PreviousCCFRI", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_ApplicationCcFri>("ccof_applicationccfri_PreviousCCFRI", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationccfri_Region
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_region")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationccfri_Region")]
		public DataverseModel.CcOf_Fee_Region CcOf_ApplicationCcFri_Region
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Fee_Region>("ccof_applicationccfri_Region", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Fee_Region>("ccof_applicationccfri_Region", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationccfri_Region3PctMedian
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_region3pctmedian")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationccfri_Region3PctMedian")]
		public DataverseModel.CcOf_Median_Fee_SdA CcOf_ApplicationCcFri_Region3PctMedian
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Median_Fee_SdA>("ccof_applicationccfri_Region3PctMedian", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Median_Fee_SdA>("ccof_applicationccfri_Region3PctMedian", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationccfri_RegionNMFBenchmark
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_regionnmfbenchmark")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationccfri_RegionNMFBenchmark")]
		public DataverseModel.CcOf_Fee_Benchmark_SdA CcOf_ApplicationCcFri_RegIoNnMfBenchmark
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Fee_Benchmark_SdA>("ccof_applicationccfri_RegionNMFBenchmark", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Fee_Benchmark_SdA>("ccof_applicationccfri_RegionNMFBenchmark", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_ccof_applicationccfri_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ccof_applicationccfri_createdby")]
		public DataverseModel.SystemUser Lk_CcOf_ApplicationCcFri_CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationccfri_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ccof_applicationccfri_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ccof_applicationccfri_createdonbehalfby")]
		public DataverseModel.SystemUser Lk_CcOf_ApplicationCcFri_CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationccfri_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationccfri_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_ccof_applicationccfri_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ccof_applicationccfri_modifiedby")]
		public DataverseModel.SystemUser Lk_CcOf_ApplicationCcFri_ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationccfri_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ccof_applicationccfri_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ccof_applicationccfri_modifiedonbehalfby")]
		public DataverseModel.SystemUser Lk_CcOf_ApplicationCcFri_ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationccfri_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationccfri_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_ccof_applicationccfri
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_ccof_applicationccfri")]
		public DataverseModel.TransactionCurrency TransactionCurrency_CcOf_ApplicationCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.TransactionCurrency>("TransactionCurrency_ccof_applicationccfri", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.TransactionCurrency>("TransactionCurrency_ccof_applicationccfri", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_ccof_applicationccfri
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_ccof_applicationccfri")]
		public DataverseModel.SystemUser User_CcOf_ApplicationCcFri
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("user_ccof_applicationccfri", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationCcFri(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ccof_applicationccfriid"] = base.Id;
                        break;
                    case "ccof_applicationccfriid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
