#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ccof_change_request_mtfi_ccof_rfipfi")]
	public partial class CcOf_Change_Request_MTfI_CcOf_RfIpFI : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the ccof_change_request_mtfi_ccof_rfipfi entity
		/// </summary>
		public partial class Fields
		{
			public const string CcOf_Change_Request_MTfI_CcOf_RfIpFI_CcOf = "ccof_Change_Request_MTFI_ccof_rfipfi_ccof";
			public const string CcOf_Change_Request_MTfI_CcOf_RfIpFIId = "ccof_change_request_mtfi_ccof_rfipfiid";
			public const string Id = "ccof_change_request_mtfi_ccof_rfipfiid";
			public const string CcOf_Change_Request_MTfIId = "ccof_change_request_mtfiid";
			public const string CcOf_RfIpFIId = "ccof_rfipfiid";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_Change_Request_MTfI_CcOf_RfIpFI(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_Change_Request_MTfI_CcOf_RfIpFI(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_Change_Request_MTfI_CcOf_RfIpFI(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_Change_Request_MTfI_CcOf_RfIpFI() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "ccof_change_request_mtfi_ccof_rfipfiid";
		
		public const string EntitySchemaName = "ccof_Change_Request_MTFI_ccof_rfipfi";
		
		public const string EntityLogicalName = "ccof_change_request_mtfi_ccof_rfipfi";
		
		public const string EntityLogicalCollectionName = null;
		
		public const string EntitySetName = "ccof_change_request_mtfi_ccof_rfipfiset";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_change_request_mtfi_ccof_rfipfiid")]
		public System.Nullable<System.Guid> CcOf_Change_Request_MTfI_CcOf_RfIpFIId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ccof_change_request_mtfi_ccof_rfipfiid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_change_request_mtfi_ccof_rfipfiid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				base.Id = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_change_request_mtfiid")]
		public System.Nullable<System.Guid> CcOf_Change_Request_MTfIId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ccof_change_request_mtfiid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_rfipfiid")]
		public System.Nullable<System.Guid> CcOf_RfIpFIId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ccof_rfipfiid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N ccof_Change_Request_MTFI_ccof_rfipfi_ccof
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_Change_Request_MTFI_ccof_rfipfi_ccof")]
		public System.Collections.Generic.IEnumerable<DataverseModel.CcOf_RfIpFI> CcOf_Change_Request_MTfI_CcOf_RfIpFI_CcOf
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DataverseModel.CcOf_RfIpFI>("ccof_Change_Request_MTFI_ccof_rfipfi_ccof", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<DataverseModel.CcOf_RfIpFI>("ccof_Change_Request_MTFI_ccof_rfipfi_ccof", null, value);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_Change_Request_MTfI_CcOf_RfIpFI(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ccof_change_request_mtfi_ccof_rfipfiid"] = base.Id;
                        break;
                    case "ccof_change_request_mtfi_ccof_rfipfiid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
