#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Status of the Application Status history
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_ApplicationStatusHistory_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Application Status history
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_ApplicationStatusHistory_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("ccof_applicationstatushistory")]
	public partial class CcOf_ApplicationStatusHistory : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the ccof_applicationstatushistory entity
		/// </summary>
		public partial class Fields
		{
			public const string Business_Unit_CcOf_ApplicationStatusHistory = "business_unit_ccof_applicationstatushistory";
			public const string CcOf_Account = "ccof_account";
			public const string CcOf_AccountName = "ccof_accountname";
			public const string CcOf_AccountType = "ccof_accounttype";
			public const string CcOf_AccountTypeName = "ccof_accounttypename";
			public const string CcOf_AccountYomiName = "ccof_accountyominame";
			public const string CcOf_Application = "ccof_application";
			public const string CcOf_ApplicationName = "ccof_applicationname";
			public const string CcOf_ApplicationStatusHistory_Account = "ccof_applicationstatushistory_account";
			public const string CcOf_ApplicationStatusHistory_Application_CcOf_Application = "ccof_applicationstatushistory_application_ccof_application";
			public const string CcOf_ApplicationStatusHistory_Change_Request = "ccof_applicationstatushistory_change_request";
			public const string CcOf_ApplicationStatusHistory_OperationUser_SystemUser = "ccof_applicationstatushistory_operationuser_systemuser";
			public const string CcOf_ApplicationStatusHistoryId = "ccof_applicationstatushistoryid";
			public const string Id = "ccof_applicationstatushistoryid";
			public const string CcOf_CcOf_ApplicationStatusHistory_CcOf_Adjudication_CcFri_CcOf_StatusHistoryRegardingId = "ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_ccof_StatusHistoryRegardingId";
			public const string CcOf_CcOf_ApplicationStatusHistory_CcOf_Adjudication_CcFri_Facility_CcOf_StatusHistoryRegardingId = "ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_facility_ccof_StatusHistoryRegardingId";
			public const string CcOf_CcOf_ApplicationStatusHistory_CcOf_Adjudication_ECEWe_CcOf_StatusHistoryRegardingId = "ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_ccof_StatusHistoryRegardingId";
			public const string CcOf_CcOf_ApplicationStatusHistory_CcOf_Adjudication_ECEWe_Facility_CcOf_StatusHistoryRegardingId = "ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_facility_ccof_StatusHistoryRegardingId";
			public const string CcOf_CcOf_ApplicationStatusHistory_CcOf_Change_Request_CcOf_StatusHistoryRegardingId = "ccof_ccof_applicationstatushistory_ccof_change_request_ccof_StatusHistoryRegardingId";
			public const string CcOf_CcOf_ApplicationStatusHistory_CcOf_Change_Request_MTfI_CcOf_StatusHistoryRegardingId = "ccof_ccof_applicationstatushistory_ccof_change_request_mtfi_ccof_StatusHistoryRegardingId";
			public const string CcOf_CcOf_ApplicationStatusHistory_SystemUser_CcOf_PostOwnerId = "ccof_ccof_applicationstatushistory_systemuser_ccof_PostOwnerId";
			public const string CcOf_CcOf_ApplicationStatusHistory_SystemUser_CcOf_PreOwnerId = "ccof_ccof_applicationstatushistory_systemuser_ccof_PreOwnerId";
			public const string CcOf_Change_Request = "ccof_change_request";
			public const string CcOf_Change_RequestName = "ccof_change_requestname";
			public const string CcOf_LogDate = "ccof_logdate";
			public const string CcOf_LookupTable = "ccof_lookuptable";
			public const string CcOf_MessageType = "ccof_messagetype";
			public const string CcOf_MessageTypeName = "ccof_messagetypename";
			public const string CcOf_Name = "ccof_name";
			public const string CcOf_OperationUser = "ccof_operationuser";
			public const string CcOf_OperationUsername = "ccof_operationusername";
			public const string CcOf_OperationUserYomiName = "ccof_operationuseryominame";
			public const string CcOf_PosTownerId = "ccof_postownerid";
			public const string CcOf_PosTownerIdName = "ccof_postowneridname";
			public const string CcOf_PosTownerIdYomiName = "ccof_postowneridyominame";
			public const string CcOf_PreOwnerId = "ccof_preownerid";
			public const string CcOf_PreOwnerIdName = "ccof_preowneridname";
			public const string CcOf_PreOwnerIdYomiName = "ccof_preowneridyominame";
			public const string CcOf_PreStatusLabel = "ccof_prestatuslabel";
			public const string CcOf_PreStatusValue = "ccof_prestatusvalue";
			public const string CcOf_StatusHistoryRegardingId = "ccof_statushistoryregardingid";
			public const string CcOf_StatusHistoryRegardingIdName = "ccof_statushistoryregardingidname";
			public const string CcOf_StatusHistoryRegardingIdYomiName = "ccof_statushistoryregardingidyominame";
			public const string CcOf_StatusLabel = "ccof_statuslabel";
			public const string CcOf_StatusValue = "ccof_statusvalue";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Lk_CcOf_ApplicationStatusHistory_CreatedBy = "lk_ccof_applicationstatushistory_createdby";
			public const string Lk_CcOf_ApplicationStatusHistory_CreatedOnBehalfBy = "lk_ccof_applicationstatushistory_createdonbehalfby";
			public const string Lk_CcOf_ApplicationStatusHistory_ModifiedBy = "lk_ccof_applicationstatushistory_modifiedby";
			public const string Lk_CcOf_ApplicationStatusHistory_ModifiedOnBehalfBy = "lk_ccof_applicationstatushistory_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningBusinessUnitName = "owningbusinessunitname";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string User_CcOf_ApplicationStatusHistory = "user_ccof_applicationstatushistory";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationStatusHistory(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationStatusHistory(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationStatusHistory(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationStatusHistory() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "ccof_applicationstatushistoryid";
		
		public const string PrimaryNameAttribute = "ccof_name";
		
		public const string EntitySchemaName = "ccof_applicationstatushistory";
		
		public const string EntityLogicalName = "ccof_applicationstatushistory";
		
		public const string EntityLogicalCollectionName = "ccof_applicationstatushistories";
		
		public const string EntitySetName = "ccof_applicationstatushistories";
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_account")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_Account
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_account");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_account", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_accountname")]
		public string CcOf_AccountName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_account"))
				{
					return this.FormattedValues["ccof_account"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_accounttype")]
		public virtual CcOf_AccountType? CcOf_AccountType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_AccountType?)(EntityOptionSetEnum.GetEnum(this, "ccof_accounttype")));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_accounttypename")]
		public string CcOf_AccountTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_accounttype"))
				{
					return this.FormattedValues["ccof_accounttype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_accountyominame")]
		public string CcOf_AccountYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_account"))
				{
					return this.FormattedValues["ccof_account"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_application")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_Application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_application");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_application", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_applicationname")]
		public string CcOf_ApplicationName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_application"))
				{
					return this.FormattedValues["ccof_application"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_applicationstatushistoryid")]
		public System.Nullable<System.Guid> CcOf_ApplicationStatusHistoryId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("ccof_applicationstatushistoryid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_applicationstatushistoryid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_applicationstatushistoryid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.CcOf_ApplicationStatusHistoryId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_change_request")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_Change_Request
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_change_request");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_change_request", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_change_requestname")]
		public string CcOf_Change_RequestName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_change_request"))
				{
					return this.FormattedValues["ccof_change_request"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_logdate")]
		public System.Nullable<System.DateTime> CcOf_LogDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("ccof_logdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_logdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_lookuptable")]
		public string CcOf_LookupTable
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ccof_lookuptable");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_lookuptable", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_messagetype")]
		public virtual CcOf_MessageType? CcOf_MessageType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_MessageType?)(EntityOptionSetEnum.GetEnum(this, "ccof_messagetype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_messagetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_messagetypename")]
		public string CcOf_MessageTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_messagetype"))
				{
					return this.FormattedValues["ccof_messagetype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_name")]
		public string CcOf_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ccof_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_operationuser")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_OperationUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_operationuser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_operationuser", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_operationusername")]
		public string CcOf_OperationUsername
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_operationuser"))
				{
					return this.FormattedValues["ccof_operationuser"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_operationuseryominame")]
		public string CcOf_OperationUserYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_operationuser"))
				{
					return this.FormattedValues["ccof_operationuser"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_postownerid")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_PosTownerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_postownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_postownerid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_postowneridname")]
		public string CcOf_PosTownerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_postownerid"))
				{
					return this.FormattedValues["ccof_postownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_postowneridyominame")]
		public string CcOf_PosTownerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_postownerid"))
				{
					return this.FormattedValues["ccof_postownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_preownerid")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_PreOwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_preownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_preownerid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_preowneridname")]
		public string CcOf_PreOwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_preownerid"))
				{
					return this.FormattedValues["ccof_preownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_preowneridyominame")]
		public string CcOf_PreOwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_preownerid"))
				{
					return this.FormattedValues["ccof_preownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_prestatuslabel")]
		public string CcOf_PreStatusLabel
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ccof_prestatuslabel");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_prestatuslabel", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_prestatusvalue")]
		public System.Nullable<int> CcOf_PreStatusValue
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("ccof_prestatusvalue");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_prestatusvalue", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingid")]
		public Microsoft.Xrm.Sdk.EntityReference CcOf_StatusHistoryRegardingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ccof_statushistoryregardingid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_statushistoryregardingid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingidname")]
		public string CcOf_StatusHistoryRegardingIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_statushistoryregardingid"))
				{
					return this.FormattedValues["ccof_statushistoryregardingid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingidyominame")]
		public string CcOf_StatusHistoryRegardingIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ccof_statushistoryregardingid"))
				{
					return this.FormattedValues["ccof_statushistoryregardingid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statuslabel")]
		public string CcOf_StatusLabel
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ccof_statuslabel");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_statuslabel", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statusvalue")]
		public System.Nullable<int> CcOf_StatusValue
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("ccof_statusvalue");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ccof_statusvalue", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("owningbusinessunit", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunitname")]
		public string OwningBusinessUnitName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("owningbusinessunit"))
				{
					return this.FormattedValues["owningbusinessunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Application Status history
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual CcOf_ApplicationStatusHistory_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_ApplicationStatusHistory_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Application Status history
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual CcOf_ApplicationStatusHistory_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((CcOf_ApplicationStatusHistory_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_ccof_applicationstatushistory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_ccof_applicationstatushistory")]
		public DataverseModel.BusinessUnit Business_Unit_CcOf_ApplicationStatusHistory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.BusinessUnit>("business_unit_ccof_applicationstatushistory", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.BusinessUnit>("business_unit_ccof_applicationstatushistory", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationstatushistory_account
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_account")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationstatushistory_account")]
		public DataverseModel.Account CcOf_ApplicationStatusHistory_Account
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.Account>("ccof_applicationstatushistory_account", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.Account>("ccof_applicationstatushistory_account", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationstatushistory_application_ccof_application
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_application")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationstatushistory_application_ccof_application")]
		public DataverseModel.CcOf_Application CcOf_ApplicationStatusHistory_Application_CcOf_Application
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Application>("ccof_applicationstatushistory_application_ccof_application", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Application>("ccof_applicationstatushistory_application_ccof_application", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationstatushistory_change_request
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_change_request")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationstatushistory_change_request")]
		public DataverseModel.CcOf_Change_Request CcOf_ApplicationStatusHistory_Change_Request
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Change_Request>("ccof_applicationstatushistory_change_request", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Change_Request>("ccof_applicationstatushistory_change_request", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_applicationstatushistory_operationuser_systemuser
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_operationuser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_applicationstatushistory_operationuser_systemuser")]
		public DataverseModel.SystemUser CcOf_ApplicationStatusHistory_OperationUser_SystemUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("ccof_applicationstatushistory_operationuser_systemuser", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("ccof_applicationstatushistory_operationuser_systemuser", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_ccof_StatusHistoryRegardingId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_ccof_StatusHistoryRega" +
			"rdingId")]
		public DataverseModel.CcOf_Adjudication_CcFri CcOf_CcOf_ApplicationStatusHistory_CcOf_Adjudication_CcFri_CcOf_StatusHistoryRegardingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Adjudication_CcFri>("ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_ccof_StatusHistoryRega" +
						"rdingId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Adjudication_CcFri>("ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_ccof_StatusHistoryRega" +
						"rdingId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_facility_ccof_StatusHistoryRegardingId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_facility_ccof_StatusHi" +
			"storyRegardingId")]
		public DataverseModel.CcOf_Adjudication_CcFri_Facility CcOf_CcOf_ApplicationStatusHistory_CcOf_Adjudication_CcFri_Facility_CcOf_StatusHistoryRegardingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Adjudication_CcFri_Facility>("ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_facility_ccof_StatusHi" +
						"storyRegardingId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Adjudication_CcFri_Facility>("ccof_ccof_applicationstatushistory_ccof_adjudication_ccfri_facility_ccof_StatusHi" +
						"storyRegardingId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_ccof_StatusHistoryRegardingId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_ccof_StatusHistoryRega" +
			"rdingId")]
		public DataverseModel.CcOf_Adjudication_ECEWe CcOf_CcOf_ApplicationStatusHistory_CcOf_Adjudication_ECEWe_CcOf_StatusHistoryRegardingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Adjudication_ECEWe>("ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_ccof_StatusHistoryRega" +
						"rdingId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Adjudication_ECEWe>("ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_ccof_StatusHistoryRega" +
						"rdingId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_facility_ccof_StatusHistoryRegardingId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_facility_ccof_StatusHi" +
			"storyRegardingId")]
		public DataverseModel.CcOf_Adjudication_ECEWe_Facility CcOf_CcOf_ApplicationStatusHistory_CcOf_Adjudication_ECEWe_Facility_CcOf_StatusHistoryRegardingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Adjudication_ECEWe_Facility>("ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_facility_ccof_StatusHi" +
						"storyRegardingId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Adjudication_ECEWe_Facility>("ccof_ccof_applicationstatushistory_ccof_adjudication_ecewe_facility_ccof_StatusHi" +
						"storyRegardingId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_ccof_applicationstatushistory_ccof_change_request_ccof_StatusHistoryRegardingId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_applicationstatushistory_ccof_change_request_ccof_StatusHistoryRegardin" +
			"gId")]
		public DataverseModel.CcOf_Change_Request CcOf_CcOf_ApplicationStatusHistory_CcOf_Change_Request_CcOf_StatusHistoryRegardingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Change_Request>("ccof_ccof_applicationstatushistory_ccof_change_request_ccof_StatusHistoryRegardin" +
						"gId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Change_Request>("ccof_ccof_applicationstatushistory_ccof_change_request_ccof_StatusHistoryRegardin" +
						"gId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_ccof_applicationstatushistory_ccof_change_request_mtfi_ccof_StatusHistoryRegardingId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_statushistoryregardingid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_applicationstatushistory_ccof_change_request_mtfi_ccof_StatusHistoryReg" +
			"ardingId")]
		public DataverseModel.CcOf_Change_Request_MTfI CcOf_CcOf_ApplicationStatusHistory_CcOf_Change_Request_MTfI_CcOf_StatusHistoryRegardingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.CcOf_Change_Request_MTfI>("ccof_ccof_applicationstatushistory_ccof_change_request_mtfi_ccof_StatusHistoryReg" +
						"ardingId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.CcOf_Change_Request_MTfI>("ccof_ccof_applicationstatushistory_ccof_change_request_mtfi_ccof_StatusHistoryReg" +
						"ardingId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_ccof_applicationstatushistory_systemuser_ccof_PostOwnerId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_postownerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_applicationstatushistory_systemuser_ccof_PostOwnerId")]
		public DataverseModel.SystemUser CcOf_CcOf_ApplicationStatusHistory_SystemUser_CcOf_PostOwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("ccof_ccof_applicationstatushistory_systemuser_ccof_PostOwnerId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("ccof_ccof_applicationstatushistory_systemuser_ccof_PostOwnerId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 ccof_ccof_applicationstatushistory_systemuser_ccof_PreOwnerId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ccof_preownerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("ccof_ccof_applicationstatushistory_systemuser_ccof_PreOwnerId")]
		public DataverseModel.SystemUser CcOf_CcOf_ApplicationStatusHistory_SystemUser_CcOf_PreOwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("ccof_ccof_applicationstatushistory_systemuser_ccof_PreOwnerId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("ccof_ccof_applicationstatushistory_systemuser_ccof_PreOwnerId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_ccof_applicationstatushistory_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ccof_applicationstatushistory_createdby")]
		public DataverseModel.SystemUser Lk_CcOf_ApplicationStatusHistory_CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationstatushistory_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ccof_applicationstatushistory_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ccof_applicationstatushistory_createdonbehalfby")]
		public DataverseModel.SystemUser Lk_CcOf_ApplicationStatusHistory_CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationstatushistory_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationstatushistory_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_ccof_applicationstatushistory_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ccof_applicationstatushistory_modifiedby")]
		public DataverseModel.SystemUser Lk_CcOf_ApplicationStatusHistory_ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationstatushistory_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_ccof_applicationstatushistory_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_ccof_applicationstatushistory_modifiedonbehalfby")]
		public DataverseModel.SystemUser Lk_CcOf_ApplicationStatusHistory_ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationstatushistory_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("lk_ccof_applicationstatushistory_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_ccof_applicationstatushistory
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_ccof_applicationstatushistory")]
		public DataverseModel.SystemUser User_CcOf_ApplicationStatusHistory
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("user_ccof_applicationstatushistory", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public CcOf_ApplicationStatusHistory(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["ccof_applicationstatushistoryid"] = base.Id;
                        break;
                    case "ccof_applicationstatushistoryid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
