#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Indicates the type of approval for approved parent fees
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_Approval_Type
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Full Approval", 0)]
		FullApproval = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Temp Approval", 1)]
		TempApproval = 2,
	}
}
#pragma warning restore CS1591
