#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_SelectTheApplicableSector
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Community Social Services Employers\' Association (CSSEA) Member", 0, "#0000ff")]
		CommunitySocialServicesEmployersAssociationCsseaMember = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("None of our facilities are unionized", 2, "#071bf0")]
		NoneOfOurFacilitiesAreUnionized = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other Unionized Employer", 1, "#2b00ff")]
		OtherUnionizedEmployer = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Some or all of our facilities are unionized", 3, "#4908fc")]
		SomeOrAllOfOurFacilitiesAreUnionized = 100000003,
	}
}
#pragma warning restore CS1591
