#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CcOf_ContractStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CONTRACT CANCELLED", 4, "#0000ff")]
		ContractCancelled = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CONTRACT CONFIRMED - ACTIVE", 0, "#0000ff")]
		ContractConfirmedActive = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CONTRACT CONFIRMED - INACTIVE", 1, "#0000ff")]
		ContractConfirmedInactive = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CONTRACT DRAFTED", 2, "#0000ff")]
		ContractDrafted = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CONTRACT TERMINATED", 3, "#0000ff")]
		ContractTerminated = 100000003,
	}
}
#pragma warning restore CS1591
